import type { WeaponId } from '../../core/types';

export type WeaponKind = 'hitscan' | 'projectile';
export type HitEffect = 'explode' | 'skid' | 'paint' | 'splat' | 'freeze' | 'wash' | 'wrap' | 'punch';
export type AfterKill = 'wreck' | 'vanish' | 'none';

export interface WeaponConfig {
  id: WeaponId;
  kind: WeaponKind;
  /** HP removed per hit (0 for paint). */
  damage: number;
  rpm: number;
  auto: boolean;
  mag: number;
  reloadMs: number;
  /** Total shots per round (undefined = unlimited). */
  perRound?: number;
  /** Hitscan spread in degrees. */
  spreadDeg: number;
  /** Projectile flight time to the aim point (s). */
  flightS?: number;
  /** Screen-space gravity for ballistic arcs (px/s² at 720p). */
  gravityPx?: number;
  /** Blast radius (px at 720p); 0 = point hit. */
  blastR: number;
  /** Rocket steering strength (0 = none). */
  homing?: number;
  effect: HitEffect;
  /** what remains of the vehicle after a kill */
  after: AfterKill;
  /** delay between impact and the skid (skid-type effects) */
  skidDelayMs?: number;
  /** decal colour for splat-type effects */
  splatColor?: string;
  /** projectile sprite */
  sprite?: 'grenade' | 'rocket' | 'milkshake' | 'egg' | 'tomato' | 'snowball' | 'balloon' | 'banana' | 'tp';
  /** points needed to unlock (0 = free) */
  price: number;
  basePoints: number;
  killBonus: number;
  /** Fractional combo increment per hit. */
  comboWeight: number;
  recoil: number;
  hitStopMs: number;
  /** Radius (px at 720p) in which a tap snaps onto a target. */
  aimAssist: number;
  ui: { damage: number; rate: number; area: number };
}

export const WEAPONS: Record<WeaponId, WeaponConfig> = {
  smg: {
    id: 'smg',
    kind: 'hitscan',
    damage: 1,
    rpm: 600,
    auto: true,
    mag: 30,
    reloadMs: 1500,
    spreadDeg: 1.3,
    blastR: 0,
    effect: 'explode',
    after: 'wreck',
    price: 0,
    basePoints: 15,
    killBonus: 120,
    comboWeight: 0.25,
    recoil: 2,
    hitStopMs: 0,
    aimAssist: 28,
    ui: { damage: 0.25, rate: 1, area: 0.05 },
  },
  grenade: {
    id: 'grenade',
    kind: 'projectile',
    damage: 8,
    rpm: 70,
    auto: false,
    mag: 6,
    reloadMs: 2400,
    spreadDeg: 0,
    flightS: 0.9,
    gravityPx: 1400,
    blastR: 95,
    effect: 'explode',
    after: 'vanish',
    price: 0,
    basePoints: 150,
    killBonus: 100,
    comboWeight: 1,
    recoil: 4,
    hitStopMs: 45,
    aimAssist: 60,
    ui: { damage: 0.8, rate: 0.25, area: 0.7 },
  },
  rocket: {
    id: 'rocket',
    kind: 'projectile',
    damage: 12,
    rpm: 40,
    auto: false,
    mag: 1,
    reloadMs: 1500,
    perRound: 3,
    spreadDeg: 0,
    flightS: 0.75,
    gravityPx: 0,
    blastR: 140,
    homing: 6,
    effect: 'explode',
    after: 'wreck',
    price: 0,
    basePoints: 250,
    killBonus: 150,
    comboWeight: 1,
    recoil: 8,
    hitStopMs: 70,
    aimAssist: 90,
    ui: { damage: 1, rate: 0.15, area: 1 },
  },
  milkshake: {
    id: 'milkshake',
    kind: 'projectile',
    damage: 0,
    rpm: 80,
    auto: false,
    mag: 5,
    reloadMs: 2000,
    spreadDeg: 0,
    flightS: 0.7,
    gravityPx: 1600,
    blastR: 0,
    effect: 'skid',
    after: 'vanish',
    skidDelayMs: 350,
    splatColor: '#fff1e0',
    sprite: 'milkshake',
    price: 0,
    basePoints: 120,
    killBonus: 80,
    comboWeight: 1,
    recoil: 3,
    hitStopMs: 40,
    aimAssist: 55,
    ui: { damage: 0.5, rate: 0.3, area: 0.2 },
  },
  paint: {
    id: 'paint',
    kind: 'hitscan',
    damage: 0,
    rpm: 300,
    auto: true,
    mag: 40,
    reloadMs: 1800,
    spreadDeg: 0.9,
    blastR: 0,
    effect: 'paint',
    after: 'none',
    price: 0,
    basePoints: 6,
    killBonus: 0,
    comboWeight: 0.2,
    recoil: 1,
    hitStopMs: 0,
    aimAssist: 24,
    ui: { damage: 0.05, rate: 0.6, area: 0.15 },
  },
  egg: {
    id: 'egg',
    kind: 'projectile',
    damage: 0,
    rpm: 110,
    auto: false,
    mag: 8,
    reloadMs: 1800,
    spreadDeg: 0,
    flightS: 0.75,
    gravityPx: 1500,
    blastR: 0,
    effect: 'splat',
    after: 'none',
    splatColor: '#ffd84d',
    sprite: 'egg',
    price: 1500,
    basePoints: 60,
    killBonus: 0,
    comboWeight: 0.6,
    recoil: 2,
    hitStopMs: 20,
    aimAssist: 55,
    ui: { damage: 0.1, rate: 0.4, area: 0.2 },
  },
  tomato: {
    id: 'tomato',
    kind: 'projectile',
    damage: 0,
    rpm: 120,
    auto: false,
    mag: 8,
    reloadMs: 1800,
    spreadDeg: 0,
    flightS: 0.7,
    gravityPx: 1500,
    blastR: 0,
    effect: 'splat',
    after: 'none',
    splatColor: '#e5322d',
    sprite: 'tomato',
    price: 2500,
    basePoints: 70,
    killBonus: 0,
    comboWeight: 0.7,
    recoil: 2,
    hitStopMs: 20,
    aimAssist: 55,
    ui: { damage: 0.1, rate: 0.45, area: 0.25 },
  },
  snowball: {
    id: 'snowball',
    kind: 'projectile',
    damage: 0,
    rpm: 90,
    auto: false,
    mag: 6,
    reloadMs: 2000,
    spreadDeg: 0,
    flightS: 0.5,
    gravityPx: 900,
    blastR: 0,
    effect: 'freeze',
    after: 'vanish',
    skidDelayMs: 650,
    splatColor: '#dff6ff',
    sprite: 'snowball',
    price: 4000,
    basePoints: 130,
    killBonus: 90,
    comboWeight: 1,
    recoil: 3,
    hitStopMs: 40,
    aimAssist: 60,
    ui: { damage: 0.55, rate: 0.35, area: 0.25 },
  },
  banana: {
    id: 'banana',
    kind: 'projectile',
    damage: 0,
    rpm: 70,
    auto: false,
    mag: 5,
    reloadMs: 2200,
    spreadDeg: 0,
    flightS: 0.6,
    gravityPx: 1900,
    blastR: 0,
    effect: 'skid',
    after: 'vanish',
    skidDelayMs: 700,
    splatColor: '#f7e26b',
    sprite: 'banana',
    price: 6000,
    basePoints: 140,
    killBonus: 90,
    comboWeight: 1,
    recoil: 2,
    hitStopMs: 40,
    aimAssist: 60,
    ui: { damage: 0.55, rate: 0.3, area: 0.2 },
  },
  waterballoon: {
    id: 'waterballoon',
    kind: 'projectile',
    damage: 0,
    rpm: 80,
    auto: false,
    mag: 6,
    reloadMs: 2000,
    spreadDeg: 0,
    flightS: 0.8,
    gravityPx: 1300,
    blastR: 0,
    effect: 'wash',
    after: 'none',
    splatColor: '#7dd3fc',
    sprite: 'balloon',
    price: 8000,
    basePoints: 90,
    killBonus: 0,
    comboWeight: 0.8,
    recoil: 3,
    hitStopMs: 30,
    aimAssist: 70,
    ui: { damage: 0.1, rate: 0.3, area: 0.6 },
  },
  tp: {
    id: 'tp',
    kind: 'projectile',
    damage: 0,
    rpm: 150,
    auto: false,
    mag: 10,
    reloadMs: 1500,
    spreadDeg: 0,
    flightS: 0.7,
    gravityPx: 1200,
    blastR: 0,
    effect: 'wrap',
    after: 'none',
    splatColor: '#f8fafc',
    sprite: 'tp',
    price: 10000,
    basePoints: 40,
    killBonus: 0,
    comboWeight: 0.5,
    recoil: 1,
    hitStopMs: 0,
    aimAssist: 55,
    ui: { damage: 0.05, rate: 0.5, area: 0.4 },
  },
  laser: {
    id: 'laser',
    kind: 'hitscan',
    damage: 0.22,
    rpm: 1200,
    auto: true,
    mag: 120,
    reloadMs: 2500,
    spreadDeg: 0,
    blastR: 0,
    effect: 'explode',
    after: 'vanish',
    price: 15000,
    basePoints: 4,
    killBonus: 150,
    comboWeight: 0.08,
    recoil: 0.3,
    hitStopMs: 0,
    aimAssist: 34,
    ui: { damage: 0.35, rate: 1, area: 0.05 },
  },
  glove: {
    id: 'glove',
    kind: 'hitscan',
    damage: 2,
    rpm: 130,
    auto: false,
    mag: Infinity,
    reloadMs: 0,
    spreadDeg: 0,
    blastR: 0,
    effect: 'punch',
    after: 'wreck',
    price: 20000,
    basePoints: 40,
    killBonus: 120,
    comboWeight: 0.6,
    recoil: 5,
    hitStopMs: 60,
    aimAssist: 50,
    ui: { damage: 0.6, rate: 0.4, area: 0.1 },
  },
};

/** Hit points per target class (SMG rounds to destroy). */
export const HP: Record<string, number> = { car: 3, truck: 6, bus: 8, train: 10, sign: 2, light: 2 };
